/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Contract } from '../../models/contract';
import { UpdateContractDto } from '../../models/update-contract-dto';

export interface ContractControllerUpdate$Params {
  id: string;
      body: UpdateContractDto
}

export function contractControllerUpdate(http: HttpClient, rootUrl: string, params: ContractControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<Contract>> {
  const rb = new RequestBuilder(rootUrl, contractControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Contract>;
    })
  );
}

contractControllerUpdate.PATH = '/contracts/{id}';
