/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Contract } from '../../models/contract';

export interface ContractControllerFindAll$Params {
}

export function contractControllerFindAll(http: HttpClient, rootUrl: string, params?: ContractControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Contract>>> {
  const rb = new RequestBuilder(rootUrl, contractControllerFindAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Contract>>;
    })
  );
}

contractControllerFindAll.PATH = '/contracts';
