/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Contract } from '../../models/contract';
import { CreateContractDto } from '../../models/create-contract-dto';

export interface ContractControllerCreate$Params {
      body: CreateContractDto
}

export function contractControllerCreate(http: HttpClient, rootUrl: string, params: ContractControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<Contract>> {
  const rb = new RequestBuilder(rootUrl, contractControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Contract>;
    })
  );
}

contractControllerCreate.PATH = '/contracts';
