/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Tax } from '../../models/tax';

export interface TaxControllerRestore$Params {
  id: string;
}

export function taxControllerRestore(http: HttpClient, rootUrl: string, params: TaxControllerRestore$Params, context?: HttpContext): Observable<StrictHttpResponse<Tax>> {
  const rb = new RequestBuilder(rootUrl, taxControllerRestore.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Tax>;
    })
  );
}

taxControllerRestore.PATH = '/taxes/{id}/restore';
