/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Tax } from '../../models/tax';

export interface TaxControllerFindAll$Params {
}

export function taxControllerFindAll(http: HttpClient, rootUrl: string, params?: TaxControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Tax>>> {
  const rb = new RequestBuilder(rootUrl, taxControllerFindAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Tax>>;
    })
  );
}

taxControllerFindAll.PATH = '/tax';
