/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyRoleEntity } from '../../models/company-role-entity';
import { CreateUserCompanyRoleDto } from '../../models/create-user-company-role-dto';

export interface UserCompanyRoleControllerCreate$Params {
      body: CreateUserCompanyRoleDto
}

export function userCompanyRoleControllerCreate(http: HttpClient, rootUrl: string, params: UserCompanyRoleControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<CompanyRoleEntity>> {
  const rb = new RequestBuilder(rootUrl, userCompanyRoleControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompanyRoleEntity>;
    })
  );
}

userCompanyRoleControllerCreate.PATH = '/user-company-role';
