/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyRoleEntity } from '../../models/company-role-entity';

export interface UserCompanyRoleControllerFindOne$Params {

/**
 * UUID del vínculo
 */
  id: string;
}

export function userCompanyRoleControllerFindOne(http: HttpClient, rootUrl: string, params: UserCompanyRoleControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<CompanyRoleEntity>> {
  const rb = new RequestBuilder(rootUrl, userCompanyRoleControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompanyRoleEntity>;
    })
  );
}

userCompanyRoleControllerFindOne.PATH = '/user-company-role/{id}';
