/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompanyRoleEntity } from '../../models/company-role-entity';
import { UpdateUserCompanyRoleDto } from '../../models/update-user-company-role-dto';

export interface UserCompanyRoleControllerUpdate$Params {

/**
 * UUID del vínculo
 */
  id: string;
      body: UpdateUserCompanyRoleDto
}

export function userCompanyRoleControllerUpdate(http: HttpClient, rootUrl: string, params: UserCompanyRoleControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<CompanyRoleEntity>> {
  const rb = new RequestBuilder(rootUrl, userCompanyRoleControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CompanyRoleEntity>;
    })
  );
}

userCompanyRoleControllerUpdate.PATH = '/user-company-role/{id}';
