/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BillingConcept } from '../../models/billing-concept';
import { UpdateBillingConceptDto } from '../../models/update-billing-concept-dto';

export interface BillingConceptControllerUpdate$Params {
  id: string;
      body: UpdateBillingConceptDto
}

export function billingConceptControllerUpdate(http: HttpClient, rootUrl: string, params: BillingConceptControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<BillingConcept>> {
  const rb = new RequestBuilder(rootUrl, billingConceptControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BillingConcept>;
    })
  );
}

billingConceptControllerUpdate.PATH = '/billing-concept/{id}';
