/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BillingConcept } from '../../models/billing-concept';

export interface BillingConceptControllerFindAll$Params {
}

export function billingConceptControllerFindAll(http: HttpClient, rootUrl: string, params?: BillingConceptControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BillingConcept>>> {
  const rb = new RequestBuilder(rootUrl, billingConceptControllerFindAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BillingConcept>>;
    })
  );
}

billingConceptControllerFindAll.PATH = '/billing-concept';
