/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Address } from '../../models/address';

export interface AddressControllerFindAllForCompany$Params {
  companyId: string;
  includeInactive: string;
}

export function addressControllerFindAllForCompany(http: HttpClient, rootUrl: string, params: AddressControllerFindAllForCompany$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Address>>> {
  const rb = new RequestBuilder(rootUrl, addressControllerFindAllForCompany.PATH, 'get');
  if (params) {
    rb.path('companyId', params.companyId, {});
    rb.query('includeInactive', params.includeInactive, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Address>>;
    })
  );
}

addressControllerFindAllForCompany.PATH = '/addresses/company/{companyId}';
