/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AddressType } from './address-type';

/**
 * Each possible value of `AddressType`
 */
export const ADDRESS_TYPE: AddressType[] = [
  'FISCAL',
  'COMMERCIAL',
  'PROPERTY',
  'OTHER'
];