/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Address {
  addressLine1: string;
  addressLine2?: string;
  city: string;

  /**
   * ID del perfil de cliente
   */
  clientProfileId?: string;

  /**
   * ID de la empresa (Tenant Isolation)
   */
  companyId?: string;
  countryCode: string;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Usuario que registró la dirección
   */
  createdByUserId?: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;
  isDefault: boolean;
  postalCode: string;
  province?: string;
  status: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';

  /**
   * ID del Arrendatario asociado
   */
  tenantId?: string;

  /**
   * FISCAL, NOTIFICACION, PROPIEDAD, etc.
   */
  type: 'FISCAL' | 'COMMERCIAL' | 'PROPERTY' | 'OTHER';

  /**
   * Fecha de última modificación
   */
  updatedAt: string;
}
