/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Address {

  /**
   * Dirección principal (Calle, número, etc.)
   */
  addressLine1: string;

  /**
   * Información adicional de la dirección (Piso, puerta, escalera)
   */
  addressLine2?: string;

  /**
   * Ciudad / municipio
   */
  city: string;

  /**
   * ID del cliente asociado a la dirección (si aplica)
   */
  clientProfileId?: string;

  /**
   * ID de la empresa propietaria de la dirección. Null si es un borrador (Draft).
   */
  companyId?: string;

  /**
   * Código de país ISO-3166-1 alpha-2
   */
  countryCode: string;

  /**
   * Fecha de creación del registro
   */
  createdAt: string;

  /**
   * ID del usuario que creó el registro. Vital para asegurar los DRAFTS huérfanos.
   */
  createdByUserId?: string;

  /**
   * Fecha de eliminación lógica (soft delete)
   */
  deletedAt?: string | null;

  /**
   * Identificador único de la entidad
   */
  id: string;

  /**
   * Indica si el registro está activo
   */
  isActive: boolean;

  /**
   * Indica si es la dirección principal para su tipo dentro de la empresa
   */
  isDefault: boolean;

  /**
   * Código postal
   */
  postalCode: string;

  /**
   * Provincia o Estado
   */
  province?: string;

  /**
   * Estado de la dirección dentro del flujo de negocio
   */
  status: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';

  /**
   * Tipo de dirección según su uso funcional
   */
  type: 'FISCAL' | 'COMMERCIAL' | 'PROPERTY' | 'OTHER';

  /**
   * Fecha de última actualización del registro
   */
  updatedAt: string;
}
