/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AddressStatus } from './address-status';

/**
 * Each possible value of `AddressStatus`
 */
export const ADDRESS_STATUS: AddressStatus[] = [
  'DRAFT',
  'ACTIVE',
  'ARCHIVED'
];