/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Propósito legal o físico de la dirección
 */
export type AddressType = 'FISCAL' | 'COMMERCIAL' | 'PROPERTY' | 'OTHER';

