/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Address {

  /**
   * ID del perfil de cliente
   */
  clientProfileId?: string;
  codigoPais: string;
  codigoPostal: string;

  /**
   * ID de la empresa (Tenant Isolation)
   */
  companyId?: string;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Usuario que registró la dirección
   */
  createdByUserId?: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};
  direccion: string;

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;
  isDefault: boolean;
  poblacion: string;
  provincia?: string;
  status: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';

  /**
   * ID del Arrendatario asociado
   */
  tenantId?: string;

  /**
   * FISCAL, NOTIFICACION, PROPIEDAD, etc.
   */
  type: 'FISCAL' | 'COMERCIAL' | 'INMUEBLE' | 'NOTIFICACION' | 'OTRA';

  /**
   * Fecha de última modificación
   */
  updatedAt: string;
}
