/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BillingConcept {
  defaultPrice: number;

  /**
   * Fecha de borrado lógico
   */
  deletedAt: string;
  id: string;
  isPriceEditable: boolean;
  isUniquePerPeriod: boolean;
  itemType: 'P' | 'S';
  label: string;
  name: string;
  requiresPeriod: boolean;
}
