/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Company } from '../models/company';
import { FiscalIdentity } from '../models/fiscal-identity';
import { User } from '../models/user';
export interface ClientProfile {

  /**
   * Email principal para facturación electrónica
   */
  billingEmail?: string;
  company: Company;

  /**
   * Fecha de creación del registro
   */
  createdAt: string;

  /**
   * Fecha de eliminación lógica (soft delete)
   */
  deletedAt?: string | null;

  /**
   * Datos fiscales validados (NIF, Razón Social)
   */
  fiscalIdentity: FiscalIdentity;

  /**
   * Identificador único de la entidad
   */
  id: string;

  /**
   * Código interno único por empresa (ej: CLI-2024-001)
   */
  internalCode: string;

  /**
   * Indica si el registro está activo
   */
  isActive: boolean;

  /**
   * Notas internas sobre el cliente (CRM)
   */
  notes?: string;

  /**
   * Días de vencimiento para cálculo automático (0 = Contado)
   */
  paymentDays: number;

  /**
   * Método de pago habitual (ej: TRANSFERENCIA, RECIBO, EFECTIVO)
   */
  paymentMethod?: string;

  /**
   * Teléfono de contacto administrativo
   */
  phone?: string;

  /**
   * Fecha de última actualización del registro
   */
  updatedAt: string;

  /**
   * Usuario vinculado para acceso al portal de clientes
   */
  user?: User;
}
