/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Company } from '../models/company';
import { User } from '../models/user';
export interface CompanyRoleEntity {

  /**
   * Empresa asociada a este nivel de autoridad
   */
  company: Company;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;

  /**
   * Rol del usuario dentro de la empresa
   */
  role: 'PROPIETARIO' | 'ARRENDATARIO' | 'GESTOR';

  /**
   * Fecha de última modificación
   */
  updatedAt: string;

  /**
   * Usuario vinculado al rol patrimonial
   */
  user: User;
}
