/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyRoleDto {

  /**
   * Identificador único de la empresa vinculada
   */
  companyId: string;

  /**
   * Nombre comercial o legal de la empresa para mostrar en el selector del Front
   */
  companyName: string;

  /**
   * Nivel de permisos del usuario dentro de esta empresa específica
   */
  role: 'OWNER' | 'TENANT' | 'VIEWER';
}
