/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { ClientProfile } from '../models/client-profile';
import { CompanyRoleEntity } from '../models/company-role-entity';
import { FiscalIdentity } from '../models/fiscal-identity';
import { Property } from '../models/property';
import { User } from '../models/user';
export interface Company {

  /**
   * Cartera de clientes de la empresa
   */
  clientProfiles?: Array<ClientProfile>;
  companyRoles: Array<Array<CompanyRoleEntity>>;

  /**
   * Fecha de creación del registro
   */
  createdAt: string;

  /**
   * Usuario creador de la empresa (solo auditoría)
   */
  createdBy?: User;

  /**
   * Usuario que creó la empresa (auditoría interna)
   */
  createdByUserId?: string;

  /**
   * Fecha de eliminación lógica (soft delete)
   */
  deletedAt?: string | null;

  /**
   * Entidad fiscal asociada a la empresa
   */
  facturaeParty: FiscalIdentity;

  /**
   * UUID de la identidad fiscal (FacturaeParty)
   */
  facturaePartyId: string;

  /**
   * Dirección fiscal de la empresa
   */
  fiscalAddress?: Address;

  /**
   * UUID de la dirección fiscal asociada
   */
  fiscalAddressId?: string;

  /**
   * Identificador único de la entidad
   */
  id: string;

  /**
   * Indica si el registro está activo
   */
  isActive: boolean;

  /**
   * Inventario de propiedades pertenecientes a esta empresa.
   */
  properties?: Array<Property>;

  /**
   * Fecha de última actualización del registro
   */
  updatedAt: string;
}
