/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Company } from '../models/company';
import { User } from '../models/user';
export interface CompanyRoleEntity {

  /**
   * Empresa a la que pertenece este rol
   */
  company: Company;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;

  /**
   * Rol del usuario dentro de la empresa
   */
  role: 'OWNER' | 'ADMIN' | 'MANAGER' | 'VIEWER';

  /**
   * Fecha de última modificación
   */
  updatedAt: string;

  /**
   * Usuario al que pertenece este rol
   */
  user: User;
}
