/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { CompanyRoleEntity } from '../models/company-role-entity';
import { FiscalEntity } from '../models/fiscal-entity';
import { Property } from '../models/property';
import { TenantProfile } from '../models/tenant-profile';
import { User } from '../models/user';
export interface Company {

  /**
   * Lista de usuarios y sus roles en esta empresa
   */
  companyRoles?: Array<CompanyRoleEntity>;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Entidad del usuario creador
   */
  createdBy?: User;

  /**
   * ID del usuario que creó el registro (Auditoría)
   */
  createdByUserId?: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};

  /**
   * Objeto completo de la identidad fiscal (Razón social, CIF...)
   */
  facturaeParty: FiscalEntity;

  /**
   * UUID de la identidad fiscal (Referencia a FacturaeParty)
   */
  facturaePartyId: string;

  /**
   * Objeto completo de la dirección fiscal
   */
  fiscalAddress?: Address;

  /**
   * UUID de la dirección fiscal asociada
   */
  fiscalAddressId?: string;

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;

  /**
   * Inventario de propiedades (inmuebles) de la empresa
   */
  properties?: Array<Property>;

  /**
   * Cartera de arrendatarios asociados al patrimonio
   */
  tenantProfiles?: Array<TenantProfile>;

  /**
   * Fecha de última modificación
   */
  updatedAt: string;
}
