/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyRole } from './company-role';

/**
 * Each possible value of `CompanyRole`
 */
export const COMPANY_ROLE: CompanyRole[] = [
  'PROPIETARIO',
  'ARRENDATARIO',
  'GESTOR'
];