/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { ClientProfile } from '../models/client-profile';
import { CompanyRoleEntity } from '../models/company-role-entity';
import { FiscalIdentity } from '../models/fiscal-identity';
import { Property } from '../models/property';
import { User } from '../models/user';
export interface Company {

  /**
   * Cartera de clientes (CRM) asociados a la empresa
   */
  clientProfiles?: Array<ClientProfile>;

  /**
   * Lista de usuarios y sus roles en esta empresa
   */
  companyRoles?: Array<CompanyRoleEntity>;

  /**
   * Fecha de creación del registro
   */
  createdAt: string;

  /**
   * Entidad del usuario creador (No se carga por defecto)
   */
  createdBy?: User;

  /**
   * ID del usuario que creó el registro (Auditoría)
   */
  createdByUserId?: string;

  /**
   * Fecha de eliminación lógica (soft delete)
   */
  deletedAt?: string | null;

  /**
   * Objeto completo de la identidad fiscal (Razón social, CIF...)
   */
  facturaeParty: FiscalIdentity;

  /**
   * UUID de la identidad fiscal (Referencia a FacturaeParty)
   */
  facturaePartyId: string;

  /**
   * Objeto completo de la dirección fiscal
   */
  fiscalAddress?: Address;

  /**
   * UUID de la dirección fiscal asociada
   */
  fiscalAddressId?: string;

  /**
   * Identificador único de la entidad
   */
  id: string;

  /**
   * Indica si el registro está activo
   */
  isActive: boolean;

  /**
   * Inventario de propiedades (inmuebles) de la empresa
   */
  properties?: Array<Property>;

  /**
   * Fecha de última actualización del registro
   */
  updatedAt: string;
}
