/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompanyMeDto {

  /**
   * ID de la empresa
   */
  companyId: string;

  /**
   * Nombre legal de la empresa
   */
  legalName: string;

  /**
   * Email del usuario OWNER
   */
  ownerEmail: string;

  /**
   * Rol del usuario autenticado en la empresa
   */
  role: 'OWNER' | 'ADMIN' | 'MANAGER' | 'VIEWER';

  /**
   * Identificación fiscal
   */
  taxId: string;

  /**
   * Nombre comercial
   */
  tradeName?: string | null;
}
