/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Company } from '../models/company';
import { User } from '../models/user';
export interface CompanyRoleEntity {

  /**
   * Empresa a la que pertenece este rol
   */
  company: Company;

  /**
   * Fecha de creación del registro
   */
  createdAt: string;

  /**
   * Fecha de eliminación lógica (soft delete)
   */
  deletedAt?: string | null;

  /**
   * Identificador único de la entidad
   */
  id: string;

  /**
   * Indica si el registro está activo
   */
  isActive: boolean;

  /**
   * Rol del usuario dentro de la empresa
   */
  role: 'OWNER' | 'ADMIN' | 'MANAGER' | 'VIEWER';

  /**
   * Fecha de última actualización del registro
   */
  updatedAt: string;

  /**
   * Usuario al que pertenece este rol
   */
  user: User;
}
