/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Contact {

  /**
   * Cargo en la empresa (opcional)
   */
  cargo?: string;

  /**
   * Fecha de creación del registro
   */
  createdAt: string;

  /**
   * Fecha de eliminación lógica (soft delete)
   */
  deletedAt?: string | null;

  /**
   * Dirección puntual del contacto (opcional)
   */
  direccion?: string;

  /**
   * Correo electrónico (opcional)
   */
  email?: string;

  /**
   * Identificador único de la entidad
   */
  id: string;

  /**
   * Indica si el registro está activo
   */
  isActive: boolean;

  /**
   * Nombre completo del contacto interno
   */
  nombre: string;

  /**
   * Teléfono de contacto (opcional)
   */
  telefono?: string;

  /**
   * Tipo de contacto interno
   */
  tipoContacto: 'DIRECCION' | 'EMERGENCIAS' | 'GESTORIA' | 'ADMINISTRACION' | 'PERSONAL' | 'OTRO' | 'General' | 'Emergencias' | 'Otro';

  /**
   * Fecha de última actualización del registro
   */
  updatedAt: string;
}
