/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Contract {

  /**
   * Fecha límite hasta la cual se permite la autofacturación (ej. Fin de los 12 meses)
   */
  autoBillingUntil: string;

  /**
   * Día programado para emitir la factura mensual (1-28)
   */
  billingDay: number;

  /**
   * Frecuencia de facturación
   */
  billingPeriod: 'MENSUAL' | 'BIMESTRAL' | 'TRIMESTRAL' | 'ANUAL';

  /**
   * ID del Cliente/Inquilino asociado
   */
  clientId: string;

  /**
   * UUID de la Cuenta Bancaria de la EMPRESA. Se mostrará en la factura para recibir Transferencias.
   */
  companyBankAccountId?: string;

  /**
   * ID de la Empresa propietaria (Owner del dato)
   */
  companyId: string;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};

  /**
   * Importe de la fianza legal depositada
   */
  depositAmount: number;

  /**
   * URL al PDF del contrato firmado
   */
  documentUrl?: string;

  /**
   * Fecha de fin de contrato (null si es indefinido)
   */
  endDate?: string;

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;

  /**
   * Si es TRUE, el sistema generará facturas automáticamente según billingDay
   */
  isAutoBillingEnabled: boolean;

  /**
   * Fecha de la última factura de renta generada con éxito
   */
  lastBillingDate?: string;

  /**
   * Importe de la renta mensual base (sin impuestos)
   */
  monthlyRent: number;

  /**
   * Método de pago oficial (01, 03, etc.)
   */
  paymentMethod: '01' | '02' | '03' | '04' | '08' | '09' | '99';

  /**
   * ID del Inmueble/Propiedad objeto del contrato
   */
  propertyId: string;

  /**
   * Referencia única del contrato (ej. Código interno)
   */
  reference: string;

  /**
   * ID de la Retención (IRPF) a restar de la renta. Viene de la entidad Tax.
   */
  retentionId?: string;

  /**
   * Fecha de inicio de vigencia
   */
  startDate: string;

  /**
   * Estado del contrato
   */
  status: 'BORRADOR' | 'ACTIVO' | 'FINALIZADO' | 'RESCINDIDO' | 'INACTIVO';

  /**
   * ID del Impuesto principal (IVA) a aplicar sobre la renta. Viene de la entidad Tax.
   */
  taxId: string;

  /**
   * UUID de la Cuenta Bancaria del CLIENTE. Se usará para girar recibos (Domiciliación).
   */
  tenantBankAccountId?: string;

  /**
   * Clasificación del contrato
   */
  type: 'ALQUILER' | 'CESION' | 'TEMPORAL' | 'OTRO';

  /**
   * Fecha de última modificación
   */
  updatedAt: string;
}
