/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Contact {

  /**
   * Cargo en la empresa (opcional)
   */
  cargo?: string;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};

  /**
   * Dirección puntual del contacto (opcional)
   */
  direccion?: string;

  /**
   * Correo electrónico (opcional)
   */
  email?: string;

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;

  /**
   * Nombre completo del contacto interno
   */
  nombre: string;

  /**
   * Teléfono de contacto (opcional)
   */
  telefono?: string;

  /**
   * Tipo de contacto interno
   */
  tipoContacto: 'DIRECCION' | 'EMERGENCIAS' | 'GESTORIA' | 'ADMINISTRACION' | 'PERSONAL' | 'OTRO' | 'General' | 'Emergencias' | 'Otro';

  /**
   * Fecha de última modificación
   */
  updatedAt: string;
}
