/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContractStatus } from './contract-status';

/**
 * Each possible value of `ContractStatus`
 */
export const CONTRACT_STATUS: ContractStatus[] = [
  'BORRADOR',
  'ACTIVO',
  'FINALIZADO',
  'RESCINDIDO'
];