/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContractStatus } from '../models/contract-status';
import { FrecuenciaPago } from '../models/frecuencia-pago';
import { MetodoPago } from '../models/metodo-pago';
import { Tax } from '../models/tax';
import { Tenant } from '../models/tenant';
export interface Contract {

  /**
   * ID de la empresa propietaria
   */
  companyId: string;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};
  diaFacturacion: number;

  /**
   * Vigencia pactada en meses
   */
  duracionMeses: number;
  estado: ContractStatus;
  fechaInicio: string;

  /**
   * Fecha de fin de contrato calculada
   */
  fechaVencimiento: string;

  /**
   * Importe de fianza
   */
  fianza: number;
  frecuenciaPago: FrecuenciaPago;

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Arrendatarios vinculados
   */
  inquilinos: Array<Tenant>;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;

  /**
   * Relación con el impuesto IVA aplicado
   */
  iva: Tax;
  metodoPago: MetodoPago;

  /**
   * ID del activo inmobiliario objeto del contrato
   */
  propertyId: string;

  /**
   * Base imponible de la renta
   */
  rentaMensual: number;

  /**
   * Relación con la retención IRPF (si aplica)
   */
  retencion: Tax;

  /**
   * Fecha de última modificación
   */
  updatedAt: string;
}
