/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateAddressDto } from '../models/create-address-dto';
import { CreateCompanyDto } from '../models/create-company-dto';
import { CreateFiscalEntityDto } from '../models/create-fiscal-entity-dto';
export interface CreateCompanyLegalDto {

  /**
   * Dirección fiscal y de notificaciones
   */
  address: CreateAddressDto;
  company: CreateCompanyDto;

  /**
   * Datos de identidad fiscal (Alineado con FacturaE/VeriFactu)
   */
  fiscal: CreateFiscalEntityDto;

  /**
   * ID del usuario al que se vinculará la entidad (Owner/Tenant/Viewer)
   */
  userId: string;
}
