/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserDto {

  /**
   * Rol global del usuario dentro del sistema
   */
  appRole?: 'SUPERADMIN' | 'ADMIN' | 'USER';

  /**
   * Correo electrónico único del usuario
   */
  email: string;

  /**
   * Contraseña del usuario (mínimo 6 caracteres)
   */
  password: string;
}
