/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyRole } from '../models/company-role';
export interface CreateUserCompanyRoleDto {

  /**
   * UUID de la empresa donde se asigna el rol
   */
  companyId: string;

  /**
   * Rol de autoridad dentro del patrimonio
   */
  role: CompanyRole;

  /**
   * UUID del usuario al que se asigna el rol
   */
  userId: string;
}
