/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTaxDto {
  facturaeCode?: string;
  isRetention?: boolean;
  name: string;
  rate: number;
  taxType: '01' | '02' | '03' | '04' | '05';
}
