/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateAddressDto } from '../models/create-address-dto';
import { CreateCompanyDto } from '../models/create-company-dto';
import { CreateFiscalDto } from '../models/create-fiscal-dto';
export interface CreateCompanyLegalDto {

  /**
   * Dirección fiscal y de notificaciones
   */
  address: CreateAddressDto;

  /**
   * Configuración de la entidad de empresa
   */
  company: CreateCompanyDto;

  /**
   * Datos de identidad fiscal (Veri*factu Compliant)
   */
  fiscal: CreateFiscalDto;

  /**
   * ID del usuario al que se vinculará la entidad (UUID v4)
   */
  userId: string;
}
