/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AddressStatus } from '../models/address-status';
import { AddressType } from '../models/address-type';
export interface CreateAddressDto {

  /**
   * Vía pública y número (Nodo <Address> en FacturaE)
   */
  addressLine1: string;

  /**
   * Información adicional (Piso, puerta, bloque...)
   */
  addressLine2?: string;

  /**
   * Ciudad o Localidad
   */
  city: string;

  /**
   * ID de la empresa (Tenant Isolation)
   */
  companyId?: string;

  /**
   * Código de país ISO 3166-1 alpha-3
   */
  countryCode: string;

  /**
   * Marca esta dirección como la principal para el sujeto
   */
  isDefault?: boolean;

  /**
   * Código Postal (Validación FacturaE)
   */
  postalCode: string;

  /**
   * Provincia o Región
   */
  province?: string;

  /**
   * Estado administrativo del registro
   */
  status?: AddressStatus;

  /**
   * Propósito legal o físico de la dirección
   */
  type: AddressType;
}
