/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateContractDto {
  autoBillingUntil?: string;

  /**
   * Día de cobro programado (1-28)
   */
  billingDay: number;
  billingPeriod: 'MENSUAL' | 'BIMESTRAL' | 'TRIMESTRAL' | 'ANUAL';

  /**
   * UUID del Cliente (Inquilino)
   */
  clientId: string;

  /**
   * UUID de la Cuenta de la Empresa (Para recibir transf.)
   */
  companyBankAccountId?: string;

  /**
   * UUID de la Empresa (Owner)
   */
  companyId: string;

  /**
   * Fianza
   */
  depositAmount: number;

  /**
   * URL del documento firmado
   */
  documentUrl?: string;
  endDate?: string;

  /**
   * Activar facturación automática
   */
  isAutoBillingEnabled: boolean;

  /**
   * Renta mensual base
   */
  monthlyRent: number;
  paymentMethod: '01' | '02' | '03' | '04' | '08' | '09' | '99';

  /**
   * UUID de la Propiedad
   */
  propertyId: string;

  /**
   * Referencia interna única
   */
  reference: string;

  /**
   * UUID de la Retención IRPF (Tax Entity)
   */
  retentionId?: string;
  startDate: string;
  status: 'BORRADOR' | 'ACTIVO' | 'FINALIZADO' | 'RESCINDIDO' | 'INACTIVO';

  /**
   * UUID del Impuesto IVA (Tax Entity)
   */
  taxId: string;

  /**
   * UUID de la Cuenta del Cliente (Para domiciliar)
   */
  tenantBankAccountId?: string;
  type: 'ALQUILER' | 'CESION' | 'TEMPORAL' | 'OTRO';
}
