/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateBillingConceptDto {
  defaultPrice?: number;
  defaultRetentionId?: string;
  defaultTaxId: string;
  isUniquePerPeriod?: boolean;
  itemType: 'P' | 'S';
  label: string;
  name: string;
  requiresPeriod?: boolean;
}
