/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCompanyDto {

  /**
   * ID de la identidad fiscal (creada en el Paso 3)
   */
  facturaePartyId: string;

  /**
   * ID de la dirección física (creada en el Paso 2)
   */
  fiscalAddressId: string;

  /**
   * ID del usuario que será el OWNER de la empresa (seleccionado/creado en el Paso 1)
   */
  userId: string;
}
