/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateFiscalIdentityDto {

  /**
   * Razón Social. **OBLIGATORIO** si personType es LEGAL_ENTITY.
   */
  corporateName?: string;

  /**
   * Código país ISO 3166-1 alpha-3. Facturae exige 3 letras (ej: ESP, FRA).
   */
  countryCode?: string;

  /**
   * Nombre de pila. **OBLIGATORIO** si personType es INDIVIDUAL.
   */
  firstName?: string;

  /**
   * Apellidos. **OBLIGATORIO** si personType es INDIVIDUAL.
   */
  lastName?: string;

  /**
   * Clasificación de la entidad: "Individual" (Autónomo) o "LegalEntity" (Empresa)
   */
  personType: 'Individual' | 'LegalEntity';

  /**
   * Código de residencia: R (España), U (UE), E (Extranjero)
   */
  residenceType?: 'R' | 'U' | 'E' | 'O';

  /**
   * Número de identificación fiscal (Sin guiones ni espacios)
   */
  taxId: string;

  /**
   * Tipo de Documento (Claves AEAT):
   *     - 01: NIF/DNI/NIE (España)
   *     - 02: NIF-IVA (Operador Intracomunitario / VIES)
   *     - 03: Pasaporte
   *     - 04: ID Extranjero (Fuera de la UE)
   */
  taxIdType: '01' | '02' | '03' | '04' | '06';

  /**
   * Régimen Fiscal (Clave AEAT): 01 (General), 07 (Criterio de Caja)...
   */
  taxRegime?: '01' | '02' | '03' | '05' | '07' | '08' | '52';

  /**
   * Nombre comercial (Marca conocida). Opcional.
   */
  tradeName?: string;
}
