/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaxType } from '../models/tax-type';
export interface CreateTaxDto {

  /**
   * Código oficial Facturae
   */
  facturaeCode?: string;
  isRetention?: boolean;
  name: string;
  rate: number;

  /**
   * Tipo lógico para Facturae
   */
  type: TaxType;
}
