/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTenantDto {

  /**
   * Código interno ERP
   */
  codigoInterno?: string;

  /**
   * Código residencia AEAT (1: Es, 2: UE, 3: Ext)
   */
  codigoResidencia?: string;

  /**
   * ID de la Dirección Fiscal
   */
  direccionFiscalId: string;
  email?: string;
  estado?: 'ACTIVO' | 'INACTIVO' | 'POTENCIAL' | 'LISTA_NEGRA';

  /**
   * ID de la Identidad Fiscal (NIF/CIF)
   */
  fiscalIdentityId: string;

  /**
   * IBAN para domiciliaciones SEPA
   */
  ibanBancario?: string;
  telefono?: string;
}
