/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateAddressDto } from '../models/create-address-dto';
export interface CreatePropertyDto {

  /**
   * Objeto de dirección física
   */
  address: CreateAddressDto;
  bathrooms?: number;
  bedrooms?: number;
  cadastralReference?: string;
  constructionYear?: number;

  /**
   * Memoria descriptiva o notas
   */
  description?: string;

  /**
   * Letra calificación energética
   */
  energyRating?: string;

  /**
   * Consumo kWh/m2 año
   */
  energyScore?: number;
  hasElevator?: boolean;
  hasParking?: boolean;
  hasStorageRoom?: boolean;
  hasTerrace?: boolean;

  /**
   * Referencia interna organizacional
   */
  internalCode: string;
  orientation?: 'NORTH' | 'SOUTH' | 'EAST' | 'WEST' | 'NORTH_EAST' | 'NORTH_WEST' | 'SOUTH_EAST' | 'SOUTH_WEST';
  status?: 'AVAILABLE' | 'RENTED' | 'RESERVED' | 'MAINTENANCE' | 'UNAVAILABLE';

  /**
   * Superficie total construida (m2)
   */
  surfaceTotal: number;

  /**
   * Superficie útil habitable (m2)
   */
  surfaceUseful: number;

  /**
   * Tipología funcional
   */
  type: 'RESIDENTIAL' | 'COMMERCIAL' | 'INDUSTRIAL' | 'PARKING' | 'STORAGE' | 'ROOM' | 'LAND' | 'OTHER';
}
