/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateAddressDto } from '../models/create-address-dto';
import { CreateFiscalEntityDto } from '../models/create-fiscal-entity-dto';
export interface CreateTenantProfileDto {

  /**
   * Dirección Fiscal Principal
   */
  address: CreateAddressDto;

  /**
   * Email específico para facturas (si es distinto al de contacto)
   */
  billingEmail?: string;

  /**
   * Datos Fiscales (NIF, Razón Social) para Facturae
   */
  fiscalIdentity: CreateFiscalEntityDto;

  /**
   * Código interno (ej: CLI-2024-001). Si se omite, se autogenera.
   */
  internalCode?: string;

  /**
   * Notas internas o observaciones sobre el cliente
   */
  notes?: string;

  /**
   * Días de vencimiento de facturas (0 = Contado)
   */
  paymentDays?: number;

  /**
   * Método de pago habitual
   */
  paymentMethod?: string;

  /**
   * Teléfono de contacto administrativo
   */
  phone?: string;
}
