/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateAddressDto } from '../models/create-address-dto';
import { CreateFiscalDto } from '../models/create-fiscal-dto';
export interface CreateCompanyDto {

  /**
   * Datos para crear una nueva dirección (Hydrated Draft)
   */
  fiscalAddress?: CreateAddressDto;

  /**
   * ID de la dirección física existente
   */
  fiscalAddressId?: string;

  /**
   * Datos para crear una nueva identidad fiscal (Hydrated Draft)
   */
  fiscalEntity?: CreateFiscalDto;

  /**
   * ID de la identidad fiscal existente
   */
  fiscalEntityId?: string;

  /**
   * ID del usuario que será el OWNER del patrimonio
   */
  userId: string;
}
