/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateAddressDto } from '../models/create-address-dto';
import { CreateFiscalDto } from '../models/create-fiscal-dto';
export interface CreateTenantProfileDto {

  /**
   * Dirección Fiscal Principal
   */
  address: CreateAddressDto;

  /**
   * Email de facturación (Veri*factu compliant).
   */
  billingEmail?: string;

  /**
   * Datos Fiscales (NIF, Razón Social) para Facturae
   */
  fiscalIdentity: CreateFiscalDto;

  /**
   * Código interno administrativo (ej: CLI-2024-001).
   */
  internalCode?: string;

  /**
   * Observaciones internas del cliente.
   */
  notes?: string;

  /**
   * Días de vencimiento (0 = Contado).
   */
  paymentDays?: number;

  /**
   * Método de pago habitual (TRANSFERENCIA, RECIBO, etc).
   */
  paymentMethod?: string;

  /**
   * Teléfono de contacto administrativo.
   */
  phone?: string;
}
