/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateAddressDto } from '../models/create-address-dto';
import { CreateFiscalEntityDto } from '../models/create-fiscal-entity-dto';
export interface CreateCompanyDto {

  /**
   * Datos para crear una nueva identidad fiscal (Draft)
   */
  facturaeParty?: CreateFiscalEntityDto;

  /**
   * ID de la identidad fiscal existente
   */
  facturaePartyId?: string;

  /**
   * Datos para crear una nueva dirección (Draft)
   */
  fiscalAddress?: CreateAddressDto;

  /**
   * ID de la dirección física existente
   */
  fiscalAddressId?: string;

  /**
   * ID del usuario que será el OWNER
   */
  userId: string;
}
