/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserCompanyRoleDto {

  /**
   * UUID de la empresa donde se asigna el rol
   */
  companyId: string;

  /**
   * Rol del usuario dentro de la empresa
   */
  role: 'OWNER' | 'ADMIN' | 'MANAGER' | 'VIEWER';

  /**
   * UUID del usuario al que se asigna el rol
   */
  userId: string;
}
