/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FiscalEntity {

  /**
   * ID de la empresa propietaria del dato (Null si es global)
   */
  companyId?: string;

  /**
   * Razón Social (Solo para Persona Jurídica)
   */
  corporateName?: string;

  /**
   * Código ISO del país (3 caracteres)
   */
  countryCode: string;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};

  /**
   * Nombre calculado para documentos oficiales
   */
  facturaeName: string;

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;

  /**
   * Nombre Legal (Solo para Persona Física)
   */
  legalName?: string;

  /**
   * Apellidos (Solo para Persona Física)
   */
  legalSurname?: string;

  /**
   * Tipo de persona: F (Física) o J (Jurídica)
   */
  personType: 'F' | 'J';

  /**
   * Tipo de residencia (Residente, UE, Extra-UE)
   */
  residenceType: 'R' | 'U' | 'E' | 'O';

  /**
   * NIF, CIF o equivalente fiscal
   */
  taxId: string;

  /**
   * Tipo de documento fiscal (01: NIF/CIF, 02: Pasaporte...)
   */
  taxIdType: '01' | '02' | '03' | '04' | '05' | '06' | '07';

  /**
   * Nombre comercial o marca conocida
   */
  tradeName?: string;

  /**
   * Fecha de última modificación
   */
  updatedAt: string;
}
