/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FiscalIdentity {

  /**
   * ID de la empresa que gestiona este dato (Null si es una identidad global)
   */
  companyId?: string;

  /**
   * Razón Social (Solo si es Persona Jurídica)
   */
  corporateName?: string;

  /**
   * Código ISO del país
   */
  countryCode: string;

  /**
   * Fecha de creación del registro
   */
  createdAt: string;

  /**
   * Fecha de eliminación lógica (soft delete)
   */
  deletedAt?: string | null;

  /**
   * Nombre calculado automáticamente según normativa FacturaE (Razón Social o Nombre+Apellidos)
   */
  facturaeName: string;

  /**
   * Identificador único de la entidad
   */
  id: string;

  /**
   * Indica si el registro está activo
   */
  isActive: boolean;

  /**
   * Nombre Legal (Solo si es Persona Física)
   */
  legalName?: string;

  /**
   * Apellidos (Solo si es Persona Física)
   */
  legalSurname?: string;

  /**
   * Tipo de persona: F (Física/Autónomo) o J (Jurídica/Empresa)
   */
  personType: 'Individual' | 'LegalEntity';

  /**
   * Tipo de residencia (Residente, UE, Extra-UE)
   */
  residenceType: 'R' | 'U' | 'E' | 'O';

  /**
   * Número de identificación fiscal
   */
  taxId: string;

  /**
   * Tipo de documento fiscal (NIF, CIF, PASAPORTE)
   */
  taxIdType: '01' | '02' | '03' | '04' | '06';

  /**
   * Nombre comercial o marca conocida
   */
  tradeName?: string;

  /**
   * Fecha de última actualización del registro
   */
  updatedAt: string;
}
