/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FiscalEntity {

  /**
   * Código ISO país (ESP)
   */
  codigoPais: string;

  /**
   * ID de la empresa propietaria (Null si es global)
   */
  companyId?: string;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;

  /**
   * NIF/CIF del obligado tributario
   */
  nif: string;

  /**
   * Nombre comercial (informativo)
   */
  nombreComercial?: string;

  /**
   * Nombre formateado para Veri*factu
   */
  nombreOficial: string;

  /**
   * Nombre y Apellidos o Razón Social Completa
   */
  nombreRazonSocial: string;

  /**
   * Tipo de documento (01: NIF, 02: Pasaporte...)
   */
  tipoIdFiscal: '01' | '02' | '03' | '04' | '05' | '06' | '07';

  /**
   * F (Física) o J (Jurídica)
   */
  tipoPersona: 'F' | 'J';

  /**
   * Residente (R), UE (U), Extra-UE (E)
   */
  tipoResidencia: 'R' | 'U' | 'E' | 'O';

  /**
   * Fecha de última modificación
   */
  updatedAt: string;
}
