/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FrecuenciaPago } from './frecuencia-pago';

/**
 * Each possible value of `FrecuenciaPago`
 */
export const FRECUENCIA_PAGO: FrecuenciaPago[] = [
  'MENSUAL',
  'BIMENSUAL',
  'TRIMESTRAL',
  'SEMESTRAL',
  'ANUAL'
];