/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LoginDto {

  /**
   * Correo electrónico del usuario
   */
  email: string;

  /**
   * Contraseña del usuario (mínimo 6 caracteres)
   */
  password: string;
}
