/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyRoleDto } from '../models/company-role-dto';
export interface MeDto {

  /**
   * Rol administrativo global que determina el acceso a funciones maestras de la App
   */
  appRole: 'SUPERADMIN' | 'ADMIN' | 'USER';

  /**
   * Perfiles adicionales de cliente si el usuario actúa como tal
   */
  clientProfiles?: Array<{
}>;

  /**
   * Listado de empresas en las que el usuario participa y su rol en cada una
   */
  companyRoles: Array<CompanyRoleDto>;

  /**
   * Timestamp de creación del usuario
   */
  createdAt: string;

  /**
   * Correo electrónico principal utilizado para login y notificaciones
   */
  email: string;

  /**
   * Nombre de pila del usuario (procedente del perfil)
   */
  firstName?: string;

  /**
   * ID único del usuario (UUID)
   */
  id: string;

  /**
   * Estado de habilitación de la cuenta en el sistema
   */
  isActive: boolean;

  /**
   * Apellidos del usuario
   */
  lastName?: string;

  /**
   * Timestamp de la última modificación de los datos del usuario
   */
  updatedAt: string;
}
