/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MetodoPago } from './metodo-pago';

/**
 * Each possible value of `MetodoPago`
 */
export const METODO_PAGO: MetodoPago[] = [
  'TRANSFERENCIA',
  'DOMICILIACION',
  'INGRESO_CUENTA',
  'EFECTIVO',
  'TARJETA',
  'BIZUM'
];