/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PersonType } from './person-type';

/**
 * Each possible value of `PersonType`
 */
export const PERSON_TYPE: PersonType[] = [
  'F',
  'J'
];