/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { Company } from '../models/company';
export interface Property {

  /**
   * Datos de localización geográfica del activo
   */
  address: Address;

  /**
   * ID físico de la dirección vinculada
   */
  addressId?: string;

  /**
   * Número de baños/aseos
   */
  bathrooms?: number;

  /**
   * Identificador oficial en el Catastro
   */
  cadastralReference?: string;

  /**
   * Relación jerárquica con la empresa
   */
  company: Company;

  /**
   * Identificador de la organización propietaria
   */
  companyId: string;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};

  /**
   * Notas adicionales o memoria descriptiva
   */
  description?: string;

  /**
   * Información de planta o altura
   */
  floor?: string;

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Código de referencia interno organizacional
   */
  internalCode: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;

  /**
   * Coordenada de latitud
   */
  latitude?: number;

  /**
   * Coordenada de longitud
   */
  longitude?: number;

  /**
   * Denominación pública del inmueble
   */
  name: string;

  /**
   * Canon de arrendamiento mensual
   */
  rentPrice?: number;

  /**
   * Número de estancias principales
   */
  rooms?: number;

  /**
   * Estado operativo actual del activo
   */
  status: 'AVAILABLE' | 'RENTED' | 'RESERVED' | 'MAINTENANCE' | 'UNAVAILABLE';

  /**
   * Superficie útil total
   */
  surfaceM2?: number;

  /**
   * Clasificación funcional del inmueble
   */
  type: 'RESIDENTIAL' | 'COMMERCIAL' | 'INDUSTRIAL' | 'PARKING' | 'STORAGE' | 'ROOM' | 'LAND' | 'OTHER';

  /**
   * Fecha de última modificación
   */
  updatedAt: string;
}
