/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
export interface Property {

  /**
   * Dirección física del inmueble
   */
  address: Address;

  /**
   * Año de construcción
   */
  anoConstruccion?: number;

  /**
   * Número de baños
   */
  'baños'?: number;

  /**
   * Calificación energética (A-G)
   */
  certificadoEnergetico?: string;

  /**
   * Código de referencia interno (ej. P01-4A)
   */
  codigoInterno: string;

  /**
   * UUID de la organización propietaria (Tenant Isolation)
   */
  companyId: string;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};

  /**
   * Número de dormitorios
   */
  dormitorios?: number;

  /**
   * Estado operativo
   */
  estado: 'DISPONIBLE' | 'ALQUILADO' | 'RESERVADO' | 'MANTENIMIENTO' | 'NO_DISPONIBLE';

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;

  /**
   * Orientación del inmueble
   */
  orientacion?: 'NORTE' | 'SUR' | 'ESTE' | 'OESTE' | 'NORESTE' | 'NOROESTE' | 'SURESTE' | 'SUROESTE';

  /**
   * Referencia Catastral oficial (20 caracteres)
   */
  referenciaCatastral?: string;

  /**
   * Superficie total construida en m²
   */
  superficieConstruida: number;

  /**
   * Superficie útil habitable en m²
   */
  superficieUtil: number;

  /**
   * ¿Tiene ascensor?
   */
  tieneAscensor: boolean;

  /**
   * ¿Tiene plaza de garaje?
   */
  tieneParking: boolean;

  /**
   * Tipología del activo (Piso, Local, etc.)
   */
  tipo: 'VIVIENDA' | 'LOCAL_COMERCIAL' | 'NAVE_INDUSTRIAL' | 'GARAJE' | 'TRASTERO' | 'HABITACION' | 'TERRENO' | 'OTRO';

  /**
   * Fecha de última modificación
   */
  updatedAt: string;
}
