/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
export interface Property {

  /**
   * Relación con la dirección física
   */
  address: Address;

  /**
   * Número de baños completos
   */
  bathrooms?: number;

  /**
   * Número de dormitorios (legales)
   */
  bedrooms?: number;

  /**
   * Identificador oficial en el Catastro
   */
  cadastralReference?: string;

  /**
   * UUID de la organización propietaria
   */
  companyId: string;

  /**
   * Año de finalización de la construcción
   */
  constructionYear?: number;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};

  /**
   * Calificación energética (A-G)
   */
  energyRating?: string;

  /**
   * Consumo de energía primaria (kWh/m² año)
   */
  energyScore?: number;

  /**
   * Indica si la finca dispone de ascensor
   */
  hasElevator: boolean;

  /**
   * Indica si dispone de plaza de garaje vinculada
   */
  hasParking: boolean;

  /**
   * Indica si dispone de trastero
   */
  hasStorageRoom: boolean;

  /**
   * Indica si el inmueble posee terraza o balcón exterior
   */
  hasTerrace: boolean;

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Código de referencia interno organizacional
   */
  internalCode: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;

  /**
   * Orientación principal del inmueble
   */
  orientation?: 'NORTH' | 'SOUTH' | 'EAST' | 'WEST' | 'NORTH_EAST' | 'NORTH_WEST' | 'SOUTH_EAST' | 'SOUTH_WEST';

  /**
   * Estado operativo actual
   */
  status: 'AVAILABLE' | 'RENTED' | 'RESERVED' | 'MAINTENANCE' | 'UNAVAILABLE';

  /**
   * Superficie total construida en m²
   */
  surfaceTotal: number;

  /**
   * Superficie útil habitable en m²
   */
  surfaceUseful: number;

  /**
   * Tipología funcional del activo
   */
  type: 'RESIDENTIAL' | 'COMMERCIAL' | 'INDUSTRIAL' | 'PARKING' | 'STORAGE' | 'ROOM' | 'LAND' | 'OTHER';

  /**
   * Fecha de última modificación
   */
  updatedAt: string;
}
