/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PropertyType } from './property-type';

/**
 * Each possible value of `PropertyType`
 */
export const PROPERTY_TYPE: PropertyType[] = [
  'RESIDENTIAL',
  'COMMERCIAL',
  'INDUSTRIAL',
  'PARKING',
  'STORAGE',
  'ROOM',
  'LAND',
  'OTHER'
];