/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PropertyStatus } from './property-status';

/**
 * Each possible value of `PropertyStatus`
 */
export const PROPERTY_STATUS: PropertyStatus[] = [
  'AVAILABLE',
  'RENTED',
  'RESERVED',
  'MAINTENANCE',
  'UNAVAILABLE'
];