/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ResidenceType } from './residence-type';

/**
 * Each possible value of `ResidenceType`
 */
export const RESIDENCE_TYPE: ResidenceType[] = [
  'R',
  'U',
  'E',
  'O'
];