/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SelectCompanyDto {

  /**
   * UUID de la empresa a la que se desea cambiar el contexto
   */
  companyId: string;
}
