/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SelectCompanyDto {

  /**
   * UUID de la empresa que el usuario quiere activar como compañía actual en sesión
   */
  companyId: string;
}
