/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaxIdType } from './tax-id-type';

/**
 * Each possible value of `TaxIdType`
 */
export const TAX_ID_TYPE: TaxIdType[] = [
  '01',
  '02',
  '03',
  '04',
  '05',
  '06',
  '07'
];