/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaxType } from './tax-type';

/**
 * Each possible value of `TaxType`
 */
export const TAX_TYPE: TaxType[] = [
  'VAT',
  'RETENTION',
  'IGIC',
  'OTHER'
];