/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Tipo de identificación (Claves AEAT): 01: NIF/CIF, 02: NIF-IVA...
 */
export type TaxIdType = '01' | '02' | '03' | '04' | '05' | '06' | '07';

