/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaxRegimeType } from './tax-regime-type';

/**
 * Each possible value of `TaxRegimeType`
 */
export const TAX_REGIME_TYPE: TaxRegimeType[] = [
  '01',
  '02',
  '03',
  '05',
  '07',
  '08',
  '09',
  '52'
];