/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Régimen de IVA aplicable (Claves VeriFactu/AEAT)
 */
export type TaxRegimeType = '01' | '02' | '03' | '05' | '07' | '08' | '09' | '52';

