/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaxType } from '../models/tax-type';
export interface Tax {

  /**
   * ID de la empresa
   */
  companyId: string;

  /**
   * Fecha de creación del registro
   */
  createdAt: string;

  /**
   * Fecha de eliminación lógica (soft delete)
   */
  deletedAt?: string | null;
  facturaeCode: string;

  /**
   * Identificador único de la entidad
   */
  id: string;

  /**
   * Indica si el registro está activo
   */
  isActive: boolean;
  isRetention: boolean;
  name: string;
  rate: number;
  type: TaxType;

  /**
   * Fecha de última actualización del registro
   */
  updatedAt: string;
}
