/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaxType } from '../models/tax-type';
export interface Tax {

  /**
   * ID de la empresa
   */
  companyId: string;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};
  facturaeCode: string;

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;
  isRetention: boolean;
  name: string;
  rate: number;
  type: TaxType;

  /**
   * Fecha de última modificación
   */
  updatedAt: string;
}
