/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaxType } from '../models/tax-type';
export interface Tax {

  /**
   * UUID de la empresa propietaria
   */
  companyId: string;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};

  /**
   * Código oficial para exportación FacturaE
   */
  facturaeCode: string;

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;

  /**
   * Define si el impuesto resta de la base (ej. IRPF)
   */
  isRetention: boolean;

  /**
   * Nombre descriptivo para listados y facturas
   */
  name: string;

  /**
   * Porcentaje impositivo (0-100)
   */
  rate: number;

  /**
   * Categorización según normativa fiscal vigente
   */
  type: TaxType;

  /**
   * Fecha de última modificación
   */
  updatedAt: string;
}
