/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
export interface Tenant {
  addresses: Array<Address>;

  /**
   * IBAN para cobros automáticos
   */
  bankAccountIban: string;
  companyId: string;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};
  email: string;
  fiscalIdentityId: string;

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Referencia interna administrativa
   */
  internalCode: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;
  phoneNumber: string;

  /**
   * Código de residencia fiscal (AEAT)
   */
  residencyCode: string;
  status: 'ACTIVE' | 'INACTIVE' | 'POTENTIAL' | 'BLACKLISTED';

  /**
   * Fecha de última modificación
   */
  updatedAt: string;
}
