/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
export interface Tenant {

  /**
   * Referencia interna administrativa
   */
  codigoInterno: string;

  /**
   * Código de residencia fiscal (1=ES, 2=UE, 3=EXT)
   */
  codigoResidencia: string;

  /**
   * UUID de la empresa propietaria
   */
  companyId: string;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};
  direcciones: Array<Address>;
  email: string;
  estado: 'ACTIVO' | 'INACTIVO' | 'POTENCIAL' | 'LISTA_NEGRA';

  /**
   * UUID de la identidad fiscal vinculada
   */
  fiscalIdentityId: string;

  /**
   * IBAN para remesas SEPA
   */
  ibanBancario: string;

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;
  telefono: string;

  /**
   * Fecha de última modificación
   */
  updatedAt: string;
}
