/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Company } from '../models/company';
import { FiscalEntity } from '../models/fiscal-entity';
import { User } from '../models/user';
export interface TenantProfile {

  /**
   * Email principal para facturación electrónica
   */
  billingEmail?: string;
  company: Company;

  /**
   * Fecha de creación
   */
  createdAt: string;

  /**
   * Sello de auditoría de borrado
   */
  deletedAt?: {
};

  /**
   * Datos fiscales validados (NIF, Razón Social)
   */
  fiscalIdentity: FiscalEntity;

  /**
   * ID único (UUID v4)
   */
  id: string;

  /**
   * Código interno único por empresa (ej: CLI-2024-001)
   */
  internalCode: string;

  /**
   * Indicador de visibilidad operativa
   */
  isActive: boolean;

  /**
   * Notas internas sobre el cliente (CRM)
   */
  notes?: string;

  /**
   * Días de vencimiento para cálculo automático (0 = Contado)
   */
  paymentDays: number;

  /**
   * Método de pago habitual (ej: TRANSFERENCIA, RECIBO, EFECTIVO)
   */
  paymentMethod?: string;

  /**
   * Teléfono de contacto administrativo
   */
  phone?: string;

  /**
   * Fecha de última modificación
   */
  updatedAt: string;

  /**
   * Usuario vinculado para acceso al portal de clientes
   */
  user?: User;
}
