/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TokensDto {

  /**
   * Access token JWT utilizado para autenticar las peticiones
   */
  accessToken: string;

  /**
   * Refresh token JWT utilizado para renovar el access token
   */
  refreshToken: string;
}
