/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateClientDto {

  /**
   * Empresa propietaria del cliente
   */
  companyId?: string;

  /**
   * Identidad fiscal del cliente (FacturaeParty)
   */
  facturaePartyId?: string;

  /**
   * Dirección fiscal del cliente
   */
  fiscalAddressId?: string;
}
