/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PersonType } from '../models/person-type';
import { ResidenceType } from '../models/residence-type';
import { TaxIdType } from '../models/tax-id-type';
import { TaxRegimeType } from '../models/tax-regime-type';
export interface UpdateFacturaePartyDto {

  /**
   * Razón Social (Obligatorio para Personas Jurídicas)
   */
  corporateName?: string;

  /**
   * Código ISO del país (3 caracteres, ej: ESP)
   */
  countryCode?: string;

  /**
   * Nombre Legal (Obligatorio para Personas Físicas)
   */
  legalName?: string;

  /**
   * Apellidos (Obligatorio para Personas Físicas)
   */
  legalSurname?: string;

  /**
   * Tipo de persona física o jurídica
   */
  personType?: PersonType;

  /**
   * Código de residencia fiscal según FacturaE
   */
  residenceType?: ResidenceType;

  /**
   * Identificación fiscal (Normalizada a mayúsculas y sin espacios)
   */
  taxId?: string;

  /**
   * Tipo de identificación (Claves AEAT): 01: NIF/CIF, 02: NIF-IVA...
   */
  taxIdType?: TaxIdType;

  /**
   * Régimen de IVA aplicable (Claves VeriFactu/AEAT)
   */
  taxRegime?: TaxRegimeType;

  /**
   * Nombre comercial (Opcional)
   */
  tradeName?: string;
}
