/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserDto {

  /**
   * Rol global del usuario dentro del sistema
   */
  appRole?: 'SUPERADMIN' | 'ADMIN' | 'USER';

  /**
   * URL de la foto de perfil
   */
  avatarUrl?: string;

  /**
   * Correo electrónico único del usuario
   */
  email?: string;

  /**
   * Nombre del usuario
   */
  firstName?: string;

  /**
   * Apellidos del usuario
   */
  lastName?: string;

  /**
   * Contraseña del usuario (mínimo 6 caracteres)
   */
  password?: string;

  /**
   * Teléfono de contacto
   */
  phone?: string;
}
