/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AddressStatus } from '../models/address-status';
import { AddressType } from '../models/address-type';
export interface UpdateFiscalAddressDto {

  /**
   * Código de país ISO 3166-1 alpha-3
   */
  codigoPais?: string;

  /**
   * Código Postal (Normativa AEAT)
   */
  codigoPostal?: string;

  /**
   * ID de la empresa (Tenant Isolation)
   */
  companyId?: string;

  /**
   * Vía pública, número, piso y puerta (Línea única para Veri*factu)
   */
  direccion?: string;

  /**
   * Marca esta dirección como la principal para el sujeto
   */
  isDefault?: boolean;

  /**
   * Localidad / Ciudad
   */
  poblacion?: string;

  /**
   * Provincia o Región
   */
  provincia?: string;

  /**
   * Estado administrativo del registro
   */
  status?: AddressStatus;

  /**
   * Propósito legal o físico de la dirección
   */
  type?: AddressType;
}
