/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserCompanyRoleDto {

  /**
   * Nuevo rol del usuario dentro de la empresa
   */
  role?: 'OWNER' | 'TENANT' | 'VIEWER';
}
