/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTenantDto {

  /**
   * ID de la empresa propietaria (Tenant Isolation)
   */
  companyId?: string;
  email?: string;

  /**
   * ID de la Identidad Fiscal legal asociada (Módulo Facturae)
   */
  fiscalIdentityId?: string;

  /**
   * Código de referencia interno para el ERP
   */
  internalCode?: string;
  status?: 'ACTIVE' | 'INACTIVE' | 'POTENTIAL' | 'BLACKLISTED';
}
