/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaxType } from '../models/tax-type';
export interface UpdateTaxDto {

  /**
   * Código oficial Facturae
   */
  facturaeCode?: string;

  /**
   * Permite activar o desactivar el impuesto para su uso en la plataforma
   */
  isActive?: boolean;
  isRetention?: boolean;
  name?: string;
  rate?: number;

  /**
   * Tipo lógico para Facturae
   */
  type?: TaxType;
}
