/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateAddressDto } from '../models/create-address-dto';
export interface UpdatePropertyDto {

  /**
   * Objeto de dirección física
   */
  address?: CreateAddressDto;

  /**
   * Año de construcción
   */
  anoConstruccion?: number;
  'baños'?: number;

  /**
   * Calificación energética (A-G)
   */
  certificadoEnergetico?: string;

  /**
   * Referencia interna (ej. P-VAL-001)
   */
  codigoInterno?: string;
  dormitorios?: number;
  estado?: 'DISPONIBLE' | 'ALQUILADO' | 'RESERVADO' | 'MANTENIMIENTO' | 'NO_DISPONIBLE';

  /**
   * Notas adicionales
   */
  notas?: string;
  orientacion?: 'NORTE' | 'SUR' | 'ESTE' | 'OESTE' | 'NORESTE' | 'NOROESTE' | 'SURESTE' | 'SUROESTE';

  /**
   * Consumo kWh/m2 año
   */
  puntuacionEnergetica?: number;

  /**
   * Referencia Catastral (Veri*factu)
   */
  referenciaCatastral?: string;

  /**
   * Superficie total construida (m2)
   */
  superficieConstruida?: number;

  /**
   * Superficie útil habitable (m2)
   */
  superficieUtil?: number;
  tieneAscensor?: boolean;
  tieneParking?: boolean;
  tieneTerraza?: boolean;
  tieneTrastero?: boolean;

  /**
   * Tipología funcional
   */
  tipo?: 'VIVIENDA' | 'LOCAL_COMERCIAL' | 'NAVE_INDUSTRIAL' | 'GARAJE' | 'TRASTERO' | 'HABITACION' | 'TERRENO' | 'OTRO';
}
