/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateAddressDto {

  /**
   * Dirección principal
   */
  addressLine1?: string;

  /**
   * Información adicional de la dirección
   */
  addressLine2?: string;

  /**
   * Ciudad / municipio
   */
  city?: string;

  /**
   * Código de país ISO-3166-1 alpha-2
   */
  countryCode?: string;

  /**
   * Indica si es la dirección principal para su tipo
   */
  isDefault?: boolean;

  /**
   * Código postal
   */
  postalCode?: string;

  /**
   * Provincia (opcional fuera de España)
   */
  province?: string;

  /**
   * Estado inicial de la dirección
   */
  status?: 'DRAFT' | 'ACTIVE' | 'ARCHIVED';

  /**
   * Tipo de dirección dentro del sistema
   */
  type?: 'FISCAL' | 'COMMERCIAL' | 'PROPERTY' | 'OTHER';
}
