/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompanyRole } from '../models/company-role';
export interface UpdateUserCompanyRoleDto {

  /**
   * Nuevo rol de autoridad dentro de la empresa
   */
  role?: CompanyRole;
}
