/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateAddressDto } from '../models/create-address-dto';
export interface UpdatePropertyDto {

  /**
   * Datos de la dirección física
   */
  address?: CreateAddressDto;
  bathrooms?: number;
  cadastralReference?: string;

  /**
   * Notas internas
   */
  description?: string;
  floor?: string;

  /**
   * Referencia interna (ej: P-VAL-001)
   */
  internalCode?: string;
  latitude?: number;
  longitude?: number;

  /**
   * Alias amigable (ej: Ático Centro)
   */
  name?: string;

  /**
   * Precio base alquiler
   */
  rentPrice?: number;
  rooms?: number;
  status?: 'AVAILABLE' | 'RENTED' | 'RESERVED' | 'MAINTENANCE' | 'UNAVAILABLE';
  surfaceM2?: number;
  type?: 'RESIDENTIAL' | 'COMMERCIAL' | 'INDUSTRIAL' | 'PARKING' | 'STORAGE' | 'ROOM' | 'LAND' | 'OTHER';
}
