/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateFiscalAddressDto {
  addressLine1?: string;
  city?: string;
  countryCode?: string;
  postalCode?: string;
}
