/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateFiscalEntityDto {
  codigoPais?: string;
  nif?: string;
  nombreComercial?: string;
  nombreRazonSocial?: string;
  tipoIdFiscal?: '01' | '02' | '03' | '04' | '05' | '06' | '07';
  tipoPersona?: 'F' | 'J';
  tipoResidencia?: 'R' | 'U' | 'E' | 'O';
}
