/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContractStatus } from '../models/contract-status';
import { FrecuenciaPago } from '../models/frecuencia-pago';
import { MetodoPago } from '../models/metodo-pago';
export interface UpdateContractDto {

  /**
   * Día del mes para emitir factura
   */
  diaFacturacion?: number;

  /**
   * Vigencia en meses
   */
  duracionMeses?: number;
  estado?: ContractStatus;
  fechaInicio?: string;
  fianza?: number;
  frecuenciaPago?: FrecuenciaPago;

  /**
   * IDs de los inquilinos firmantes (Mínimo 1)
   */
  inquilinosIds?: Array<string>;
  metodoPago?: MetodoPago;

  /**
   * ID del inmueble objeto del alquiler
   */
  propertyId?: string;
  rentaMensual?: number;

  /**
   * ID del impuesto IRPF (Tax)
   */
  taxIrpfId?: string;

  /**
   * ID del impuesto IVA (Tax)
   */
  taxIvaId?: string;
}
