/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateContactDto {

  /**
   * Cargo en la empresa (opcional)
   */
  cargo?: string;

  /**
   * Dirección postal del contacto (opcional)
   */
  direccion?: string;

  /**
   * Correo electrónico del contacto (opcional)
   */
  email?: string;

  /**
   * Activo/inactivo (opcional, por defecto activo)
   */
  isActive?: boolean;

  /**
   * Nombre completo del contacto interno
   */
  nombre?: string;

  /**
   * Teléfono del contacto (opcional)
   */
  telefono?: string;

  /**
   * Tipo de contacto interno
   */
  tipoContacto?: 'DIRECCION' | 'EMERGENCIAS' | 'GESTORIA' | 'ADMINISTRACION' | 'PERSONAL' | 'OTRO' | 'General' | 'Emergencias' | 'Otro';
}
