/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateAddressDto } from '../models/create-address-dto';
import { PropertyStatus } from '../models/property-status';
import { PropertyType } from '../models/property-type';
export interface UpdatePropertyDto {

  /**
   * Dirección física
   */
  address?: CreateAddressDto;
  bathrooms?: number;
  cadastralReference?: string;

  /**
   * Notas internas
   */
  description?: string;
  floor?: string;

  /**
   * Referencia interna única
   */
  internalCode?: string;
  latitude?: number;
  longitude?: number;

  /**
   * Alias del inmueble
   */
  name?: string;

  /**
   * Precio base alquiler
   */
  rentPrice?: number;
  rooms?: number;
  status?: PropertyStatus;
  surfaceM2?: number;
  type?: PropertyType;
}
