/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaxType } from '../models/tax-type';
export interface UpdateTaxDto {

  /**
   * Causa de exención AEAT (ej: E1 para alquiler vivienda)
   */
  causaExencion?: string;

  /**
   * Código oficial FacturaE (IVA=01, IRPF=02)
   */
  codigoFacturae?: string;

  /**
   * Si es true, el valor resta de la base imponible
   */
  esRetencion?: boolean;

  /**
   * Estado de disponibilidad operativa del impuesto
   */
  isActive?: boolean;

  /**
   * Nombre descriptivo para la factura
   */
  nombre?: string;

  /**
   * Porcentaje impositivo (0 a 100)
   */
  porcentaje?: number;

  /**
   * Categorización lógica del impuesto
   */
  tipo?: TaxType;
}
