/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UpdateFacturaePartyDto } from '../models/update-facturae-party-dto';
import { UpdateFiscalAddressDto } from '../models/update-fiscal-address-dto';
export interface UpdateCompanyDto {
  email?: string;
  facturaeParty?: UpdateFacturaePartyDto;
  fiscalAddress?: UpdateFiscalAddressDto;
  phone?: string;
}
