/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {

  /**
   * Rol de acceso global a la plataforma
   */
  appRole: 'SUPERADMIN' | 'ADMIN' | 'USER';

  /**
   * Fecha de creación del registro
   */
  createdAt: string;
  email: string;

  /**
   * Nombre de pila del usuario
   */
  firstName?: string;

  /**
   * Identificador único (UUID v4)
   */
  id: string;

  /**
   * Estado de la cuenta (activo/inactivo)
   */
  isActive: boolean;

  /**
   * Apellidos del usuario
   */
  lastName?: string;

  /**
   * Fecha de la última actualización
   */
  updatedAt: string;
}
