/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientProfile } from '../models/client-profile';
import { CompanyRoleEntity } from '../models/company-role-entity';
export interface User {

  /**
   * Rol global del usuario (SUPERADMIN, ADMIN, USER)
   */
  appRole: 'SUPERADMIN' | 'ADMIN' | 'USER';

  /**
   * URL de la foto de perfil
   */
  avatarUrl?: string;

  /**
   * Perfiles de cliente asociados a este usuario
   */
  clientProfiles?: Array<ClientProfile>;

  /**
   * Roles del usuario en diferentes empresas (OWNER, CLIENT, etc.)
   */
  companyRoles?: Array<CompanyRoleEntity>;

  /**
   * Fecha de creación del registro
   */
  createdAt: string;

  /**
   * Fecha de eliminación lógica (soft delete)
   */
  deletedAt?: string | null;

  /**
   * Correo electrónico único del usuario
   */
  email: string;

  /**
   * Nombre
   */
  firstName?: string;

  /**
   * Identificador único de la entidad
   */
  id: string;

  /**
   * Indica si el registro está activo
   */
  isActive: boolean;

  /**
   * Estado de verificación del email
   */
  isEmailVerified: boolean;

  /**
   * Apellidos
   */
  lastName?: string;

  /**
   * Contraseña (Hashed)
   */
  password: string;

  /**
   * Teléfono
   */
  phone?: string;

  /**
   * Fecha de última actualización del registro
   */
  updatedAt: string;
}
