/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateFiscalEntityDto } from '../../models/create-fiscal-entity-dto';
import { FiscalEntity } from '../../models/fiscal-entity';

export interface FiscalIdentityControllerCreate$Params {
      body: CreateFiscalEntityDto
}

export function fiscalIdentityControllerCreate(http: HttpClient, rootUrl: string, params: FiscalIdentityControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<FiscalEntity>> {
  const rb = new RequestBuilder(rootUrl, fiscalIdentityControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FiscalEntity>;
    })
  );
}

fiscalIdentityControllerCreate.PATH = '/fiscal-identities';
