/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Property } from '../../models/property';

export interface PropertyControllerRemove$Params {
  id: string;
}

export function propertyControllerRemove(http: HttpClient, rootUrl: string, params: PropertyControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<Property>> {
  const rb = new RequestBuilder(rootUrl, propertyControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Property>;
    })
  );
}

propertyControllerRemove.PATH = '/properties/{id}';
