/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Property } from '../../models/property';

export interface PropertyControllerFindTrash$Params {
}

export function propertyControllerFindTrash(http: HttpClient, rootUrl: string, params?: PropertyControllerFindTrash$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Property>>> {
  const rb = new RequestBuilder(rootUrl, propertyControllerFindTrash.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Property>>;
    })
  );
}

propertyControllerFindTrash.PATH = '/properties/trash';
